
OLED_ENABLE = no
#OLED_DRIVER = SSD1306
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
#RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
#RGB_MATRIX_DRIVER = ws2812

#POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER = azoteq_iqs5xx

